version: '3'

services:
  app:
    build: ./
    container_name: 'JavaTelegramBot'
    ports:
      - 8084:8084
    depends_on:
      - postgres
      - kafka
    environment:
      - SERVER_PORT= 8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/zskhelper_db
    networks:
      - bot-network
      - kafka-networks
    links:
      - kafka-ui

  app2:
    build:
      context: /Users/olegsmyslaev/Desktop/bot/ZSKHelperHostAPI/
      dockerfile: Dockerfile
    container_name: 'BotServer'
    ports:
      - 8085:8085
    depends_on:
      - postgres
      - kafka
    environment:
      - SERVER_PORT= 8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/zskhelper_db
    networks:
      - bot-network
      - kafka-networks
    links:
      - kafka-ui

  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: 'bot-postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes:
      - ./createDataBase.sql:/docker-entrypoint-initdb.d/createDataBase.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - bot-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'zookeeper'
    networks:
      - kafka-networks
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: 'kafka'
      networks:
        - kafka-networks
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      hostname: kafka
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092, INTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092, EXTERNAL_SAME_HOST://:localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      ports:
        - 8090:8080
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      links:
        - kafka
        - zookeeper

volumes:
  db-data:
  pgadmin-data:

networks:
  bot-network:
    driver: bridge
  kafka-networks:
    driver: bridge



